### ISSUE TITLE
As a Rat I want an automatically generated error report which may be easily send to the tech rats.

### ISSUE THREAD

**Issue by UncleClapton** [FuelRats/fuelrats.com#350]
## Acceptance Criteria

- [ ] A button is displayed on all API Errors which generates an error report from the redux action.
- [ ] This error report MUST:
  - [ ] Be uploaded to `paste.fuelrats.com`
  - [ ] Be censored of any sensitive information.
  - [ ] Passwords, auth tokens, and emails are the biggest issues. These are in predictable places with predictable keys, however, so it shouldn't be too difficult to catch everything.
- [ ] A method of sending this report should be provided.

## Background

We should have an option added to `<ApiErrorBox />` which auto-generates error report documents and posts them to {{paste.fuelrats.com}}.

## Additional Information

The final method of sending this report is still in flux. just some ideas:
* Just provide a link to our support email and have the user email the report link to us,
* Fully generate and submit the report on the server end with a single click.
  * If we do this, the report should be submitted as a helpdesk ticket, and ideally we have a modal open up to have the user submit some basic contact information along with it.

**Comment by evertiro** [comment]
Any further thoughts on how this should be implemented we've come up with in the last three years?
