### ISSUE TITLE
Avatar Uploader Improvements

### ISSUE THREAD

**Issue by UncleClapton** [FuelRats/fuelrats.com#355]
- [x] File input can/should be styled to include a drop zone which responds to a hovering file (again the original file uploader from rollforguild had this, we can pull from that.)
- [x] Crop tool should be hidden until there is a file to crop
- [x] Some "stop points" for rotate should be added (if possible). maybe in 45deg increments each way, perhaps.
- [x] Theming for rc-slider would be a nice-to-have. maybe modeled after the switch input. ditch the side icons, use a single center icon in the slider handle to represent what the slider is for.
- [x] Some changes to submission flow should be considered.
  - [x] After avatar submission has begun, inputs in the modal should be disabled and have a visible change to clearly convey a pending state.
  - [x] If avatar submission fails, controls of the modal should be restored.
- [x] Styling of the avatar on the profile page still needs to be looked at to resolve that "pop-in" layout breaking effect.
- [x] #374
- [x] The `selectAvatarByUserId()` selector needs to be modified in the following ways
  - [x] `user.attributes.image` has become `user.relationships.avatar`. Avatars are now represented as a relationship instead, so we need to check if the relationship exists to determine if the user's avatar should be used.
  - [x] The ID of the avatar resource should be used to cache bust the user's avatar. this should result in the avatar path to appear like: ```url = `/api/fr/:userId/image?v=${user.relationships.avatar.data.id}\` ```

**Comment by UncleClapton** [comment]
@Pero-Moretti note changes on task list. last 2 points are new tasks required. I have also created an "epic" label which has been added to the ticket.
