### ISSUE TITLE
As a Epic Rat with an old legacy certificate I want to have the opportunity to request a new certificate

### ISSUE THREAD

**Issue by UncleClapton** [FuelRats/fuelrats.com#386]
## Acceptance Criteria

- [ ] I want to see a "Epics" tab on the user profile **if the user has an epic**
- [ ] Contents Epics Tab meets the following criteria
 	- [ ] I want to see a form that accepts the following fields
    	- Rat (Dropdown) (required)
    	- Rat's Full name (required)
    	- Shipping Address (required)
    	- Shipping City (required)
    	- Shipping State/Region (required if country has region)
    	- Shipping PostCode (required)
    	- Shipping Country (required)
    	- Submit button
    - [ ] When I press the submit button, if all required fields are filled I want the form to be submitted to the epic cert API (
  		- TODO: full URL to be determined later) 
  	- [ ] I want to see a text block explaining if I already have a certificate and want a new one, I should contact a quartermaster rat.
  
## Additional Information

Copy for text block:

> TODO

Object to pass to API is as such:

```ts
interface CertBase {
  ratId: string; // Inferred from rat dropdown
  userId: string; // current user ID
  cmdrname: string; // Inferred from rat dropdown
  email: string; // current user email
  address?: string; 
  fullname?: string;
  postcode?: string; // ZIP code
  postname?: string; // City
  region?: string; // state/region
  country?: string;
}
```
